// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/estkungzc/go/src/covidTrackingApi/service/covid_tracker.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/estkungzc/covidTrackingApi/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCovidTrackerService is a mock of CovidTrackerService interface.
type MockCovidTrackerService struct {
	ctrl     *gomock.Controller
	recorder *MockCovidTrackerServiceMockRecorder
}

// MockCovidTrackerServiceMockRecorder is the mock recorder for MockCovidTrackerService.
type MockCovidTrackerServiceMockRecorder struct {
	mock *MockCovidTrackerService
}

// NewMockCovidTrackerService creates a new mock instance.
func NewMockCovidTrackerService(ctrl *gomock.Controller) *MockCovidTrackerService {
	mock := &MockCovidTrackerService{ctrl: ctrl}
	mock.recorder = &MockCovidTrackerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCovidTrackerService) EXPECT() *MockCovidTrackerServiceMockRecorder {
	return m.recorder
}

// GetCovidStat mocks base method.
func (m *MockCovidTrackerService) GetCovidStat() model.CovidClientResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCovidStat")
	ret0, _ := ret[0].(model.CovidClientResponse)
	return ret0
}

// GetCovidStat indicates an expected call of GetCovidStat.
func (mr *MockCovidTrackerServiceMockRecorder) GetCovidStat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCovidStat", reflect.TypeOf((*MockCovidTrackerService)(nil).GetCovidStat))
}

// GetCovidSummary mocks base method.
func (m *MockCovidTrackerService) GetCovidSummary() model.CovidSummaryResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCovidSummary")
	ret0, _ := ret[0].(model.CovidSummaryResponse)
	return ret0
}

// GetCovidSummary indicates an expected call of GetCovidSummary.
func (mr *MockCovidTrackerServiceMockRecorder) GetCovidSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCovidSummary", reflect.TypeOf((*MockCovidTrackerService)(nil).GetCovidSummary))
}
