name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Running the Unit Tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Building image
        uses: actions/docker/cli@master
        with:
          args: build -t estkungzc/covid-tracking-api:latest .

#      - name: docker login
#        uses: actions/docker/login@master
#        env:
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#
#      - name: docker push
#        uses: actions/docker/cli@master
#        with:
#          args: push estkungzc/covid-tracking-api:latest